name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Set the branch you want to analyze (e.g., `main`, `master`)
  pull_request:
    branches:
      - main  # Analyze pull requests to the main branch

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: IMRAAN
          token: ${{ secrets.4bbe31a7f5fbc697559cdc496efa69c345b0f80f }}
